### GENERAL SETTINGS ###
name: "MinCoin"
logo: "/images/cropped-mincoin-logo-png.png"
description: "Official MinCoin Website"
author: "John"
email: webuimaker@gmail.com
url: ""
github : username
twitter : username
#baseurl: /Blog
#navigation:
# - title: Home
#   url: /index.html
# - title: About Us
#   url: /about.html
# - title: Category
#   url: /category.html
# - title: Contact
#   url: /contact.html
   
###disqus: disqusId



gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock   
### pagination
paginate: 4
paginate_path: "/blog/page:num/"

# Lang settings
default_lang: 'en'
langs:
  'en': 'English'
  'fr': 'Français'
  'de': 'Deutsche'
lang_codes:
  - 'en'
  - 'fr'
  - 'de'
