### GENERAL SETTINGS ###
name: "MinCoin"
logo: "/images/cropped-mincoin-logo-png.png"
description: "Official MinCoin Website"
author: "John"
email: webuimaker@gmail.com
url: ""
github : username
twitter : username

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock   
### pagination
paginate: 4
paginate_path: "/blog/page:num/"

# Lang settings
default_lang: 'en'
langs:
  'en': 'English'
  'fr': 'Français'
  'de': 'Deutsche'
  #'nl': 'Nederlands'
lang_codes:
  - 'en'
  - 'fr'
  - 'de'
  - 'nl'
