### GENERAL SETTINGS ###
name: "MinCoin"
logo: "/images/cropped-mincoin-logo-png.png"
description: "Official MinCoin Website"
author: "John"
email: webuimaker@gmail.com
url: "https://www.mincoinfoundation.com"
github : username
twitter : username

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock   
### pagination
paginate: 4
paginate_path: "/blog/page:num/"
# Lang settings
default_lang: 'en'
langs:
  'en': 'English'
  'nl': 'Netherlands'
  'vi': 'Việt'
  'de': 'Deutsch'
  'jv': 'Javanese'
  'ru': 'Русский'
  'tr': 'Türkçe'  
  'ja': '日本語' 
  'ko': '한국어' 
  'bn': 'বাংলা' 
  'ar': 'العَرَبِيَّة‎'
  'zh-hans': '繁體中文'
  'zh-hant': '中文'    
lang_codes:
  - 'en'
  - 'nl'
  - 'vi'
  - 'de'
  - 'jv'
  - 'ru'
  - 'tr'
  - 'ja'
  - 'ko'
  - 'bn'
  - 'ar'
  - 'zh-hans'
  - 'zh-hant'
